
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'etl_demo_transform'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'etl_demo_transform'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
log-path: "logs"


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  etl_demo_transform:
    stage:
      tags:
        - stage
      enabled: true
      +materialized: view
    etl_demo:
      tags:
        - etl_demo
      enabled: true
      hubs:
        tags:
          - hub
      links:
        tags:
          - link
      satellites:
        tags:
          - sat
