etl_demo_transform:
  outputs:
    dev:
      type: greenplum
      threads: 3
      host: "{{ env_var('DWH_HOST') }}"
      port: "{{ env_var('DWH_PORT') | as_number }}"
      user: "{{ env_var('DWH_USER') }}"
      pass: "{{ env_var('DWH_PASSWD') }}"
      dbname: "{{ env_var('DWH_DBNAME') }}"
      schema: "{{ env_var('DWH_SCHEMA') }}"
      sslmode: verify-full

  target: dev
